### PR TITLE
Auto l1 addr

### LINKED ISSUE #17: Automatically add L1 token address
When adding a new token with `scripts/add-token.js`, try to get the L1 token address and, if found, add it.

The tests in `test/hemi.tokenlist.test.js` should also check the address in the list is correct (matches if present, call fails if not).

### PR DESCRIPTION
**Pull request by gabmontes**
Resolves #17.

Review commit by commit. It is pretty straightforward and self-explanatory that way.

### CODE REVIEW

**Review by ArturDolzan — APPROVED** [review]

File: scripts/add-token.js [hunk 1]
```diff
@@ -3,36 +3,34 @@ import {
...
   http,
-  isAddress,
   isAddressEqual,
 } from "viem";
 import { hemi, hemiSepolia } from "hemi-viem";
 import fs from "node:fs";
 
-// eslint fails to parse "with { type: "json" }"
-// See https://github.com/eslint/eslint/discussions/15305
-const tokenList = JSON.parse(fs.readFileSync("./src/hemi.tokenlist.json"));
```
Comment (gndelia) [inline scripts/add-token.js:14]: Just to clarify:

This comment mentioned that using

```tsx
import tokenList from './src/hemi.tokenlist.json' with { type: "json" } 
```

works but throws an eslint error, and that's why we're using `fs`

**Review by gndelia — APPROVED** [review]
